version: 2
jobs:
  build:
    docker: # See https://docs.docker.com/get-started/#docker-concepts if you are new to Docker.
      - image: behdad222/android-sdk:v2.0.0
      
    steps:
      - checkout
      - run: ./gradlew assemble
